### PR TITLE
ROS1/ROS2 Hybrid: pacmod_msgs

### PR DESCRIPTION
**Pull request by JWhitleyAStuff**
This is the final AutonomouStuff message package which is being hybridized to be able to be built in both ROS1 Kinetic/Melodic and ROS2 Dashing. CI on this branch is now running all 3 environments.

I've included at least one member from each engineering team to make sure that everyone has a chance to give feedback and we don't merge this until we're sure that nothing will break. After the following tasks are complete and I have an accepted review from each team, we will merge this in tandem with the changes to the other nodes that it effects. Here are the items that I know of (currently) that need to be completed before this can be merged:

- [x] Update pacmod3 driver to match message changes (astuff/pacmod3#59)
- [x] Add and test bag migration rules
- [x] Test all changes on real sensor
If there are other items that need to be updated to coincide with this merge, please speak up and I'll add them to this list. Thanks!

### CODE REVIEW

**Comment by as-snehagn** [comment]
@JWhitleyAStuff Do we want to completely remove the PID reports from pacmod_msgs before merging this one?

**Comment by JWhitleyAStuff** [comment]
> @JWhitleyAStuff Do we want to completely remove the PID reports from pacmod_msgs before merging this one?

The reason I would say no is that this would break currently-running PACMod drivers and force users to upgrade. If they want to upgrade the messages (for example, for another driver), I don't want to force them to also have to upgrade the PACMod driver.

**Comment by JWhitleyAStuff** [comment]
@as-snehagn - Were you able to test these changes on a real vehicle?

**Comment by as-snehagn** [comment]
@JWhitleyAStuff Yes, Travis tested it yesterday and I ran it with SSC as well. Did not run into anything major.

**Pull request merged**
